language: csharp
solution: Confie.ServiceLayer.sln
install:
  - nuget restore Confie.ServiceLayer.sln
  - nuget install NUnit.ConsoleRunner -Version 3.8.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug Confie.ServiceLayer.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./src/Libraries/Infrastructure/Confie.Infrastructure.UnitTests/bin/Debug/Confie.Infrastructure.UnitTests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./src/Libraries/Domains/Vendors/Confie.Vendors.UnitTests/bin/Debug/Confie.Vendors.UnitTests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./src/Applications/Vendors/WesternGeneral/Confie.WesternGeneral.UnitTests/bin/Debug/Confie.WesternGeneral.UnitTests.dll